services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://surya:12345@cluster0.ss9fdyp.mongodb.net/ecommerce
      - key: JWT_SECRET
        value: your_secret
      - key: GOOGLE_CLIENT_ID
        value: 945378493134-ju2ben46osdq1r98akrq36kmg3ojd3fl.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_CALLBACK_URL
        value: https://ecommerce-backend.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://e-commerce-brdq.onrender.com
      - key: CLOUDINARY_URL
        value: cloudinary://671361884816884:LfHrlFJtfwWb4MbFzBgYDJ2VeW4@djfh1ooz6
