export const products = [
    // ================= SNACKS =================
    {
        name: "Potato Chips",
        unit: "200g",
        price: 60,
        image: "https://res.cloudinary.com/demo/image/upload/potato_chips.jpg",
        categoryName: "Snacks",
    },
    {
        name: "Chocolate Cookies",
        unit: "300g",
        price: 120,
        image: "https://res.cloudinary.com/demo/image/upload/cookies.jpg",
        categoryName: "Snacks",
    },
    {
        name: "Salted Nuts",
        unit: "250g",
        price: 220,
        image: "https://res.cloudinary.com/demo/image/upload/salted_nuts.jpg",
        categoryName: "Snacks",
    },
    {
        name: "Granola Bar",
        unit: "6 pcs",
        price: 180,
        image: "https://res.cloudinary.com/demo/image/upload/granola.jpg",
        categoryName: "Snacks",
    },
    {
        name: "Pretzels",
        unit: "200g",
        price: 95,
        image: "https://res.cloudinary.com/demo/image/upload/pretzels.jpg",
        categoryName: "Snacks",
    },
    {
        name: "Cheese Crackers",
        unit: "250g",
        price: 110,
        image: "https://res.cloudinary.com/demo/image/upload/cheese_crackers.jpg",
        categoryName: "Snacks",
    },
    {
        name: "Energy Bites",
        unit: "10 pcs",
        price: 250,
        image: "https://res.cloudinary.com/demo/image/upload/energy_bites.jpg",
        categoryName: "Snacks",
    },

    // ================= PET CARE =================
    {
        name: "Dog Food",
        unit: "5kg",
        price: 1400,
        image: "https://res.cloudinary.com/demo/image/upload/dogfood.jpg",
        categoryName: "Pet Care",
    },
    {
        name: "Cat Food",
        unit: "3kg",
        price: 1200,
        image: "https://res.cloudinary.com/demo/image/upload/cat_food.jpg",
        categoryName: "Pet Care",
    },
    {
        name: "Pet Shampoo",
        unit: "500ml",
        price: 350,
        image: "https://res.cloudinary.com/demo/image/upload/pet_shampoo.jpg",
        categoryName: "Pet Care",
    },
    {
        name: "Dog Toy",
        unit: "1 pc",
        price: 300,
        image: "https://res.cloudinary.com/demo/image/upload/dog_toy.jpg",
        categoryName: "Pet Care",
    },
    {
        name: "Cat Litter",
        unit: "10kg",
        price: 900,
        image: "https://res.cloudinary.com/demo/image/upload/cat_litter.jpg",
        categoryName: "Pet Care",
    },

    // ================= HOME & CLEANING =================
    {
        name: "Laundry Detergent",
        unit: "2L",
        price: 420,
        image: "https://res.cloudinary.com/demo/image/upload/detergent.jpg",
        categoryName: "Home & Cleaning",
    },
    {
        name: "Floor Cleaner",
        unit: "2L",
        price: 280,
        image: "https://res.cloudinary.com/demo/image/upload/floor_cleaner.jpg",
        categoryName: "Home & Cleaning",
    },
    {
        name: "Glass Cleaner",
        unit: "500ml",
        price: 160,
        image: "https://res.cloudinary.com/demo/image/upload/glass_cleaner.jpg",
        categoryName: "Home & Cleaning",
    },
    {
        name: "Paper Towels",
        unit: "6 rolls",
        price: 240,
        image: "https://res.cloudinary.com/demo/image/upload/paper_towels.jpg",
        categoryName: "Home & Cleaning",
    },
    {
        name: "Trash Bags",
        unit: "30 pcs",
        price: 190,
        image: "https://res.cloudinary.com/demo/image/upload/trash_bags.jpg",
        categoryName: "Home & Cleaning",
    },
    {
        name: "Sponge Pack",
        unit: "5 pcs",
        price: 120,
        image: "https://res.cloudinary.com/demo/image/upload/sponge_pack.jpg",
        categoryName: "Home & Cleaning",
    },
    {
        name: "Toilet Cleaner",
        unit: "750ml",
        price: 180,
        image: "https://res.cloudinary.com/demo/image/upload/toilet_cleaner.jpg",
        categoryName: "Home & Cleaning",
    },

    // ================= DAIRY =================
    {
        name: "Milk",
        unit: "1L",
        price: 60,
        image: "https://res.cloudinary.com/demo/image/upload/milk.jpg",
        categoryName: "Dairy",
    },
    {
        name: "Cheese",
        unit: "500g",
        price: 260,
        image: "https://res.cloudinary.com/demo/image/upload/cheese.jpg",
        categoryName: "Dairy",
    },
    {
        name: "Butter",
        unit: "250g",
        price: 140,
        image: "https://res.cloudinary.com/demo/image/upload/butter.jpg",
        categoryName: "Dairy",
    },
    {
        name: "Yogurt",
        unit: "500g",
        price: 75,
        image: "https://res.cloudinary.com/demo/image/upload/yogurt.jpg",
        categoryName: "Dairy",
    },
    {
        name: "Cream",
        unit: "250ml",
        price: 90,
        image: "https://res.cloudinary.com/demo/image/upload/cream.jpg",
        categoryName: "Dairy",
    },
    {
        name: "Paneer",
        unit: "500g",
        price: 240,
        image: "https://res.cloudinary.com/demo/image/upload/paneer.jpg",
        categoryName: "Dairy",
    },

    // ================= COOKING =================
    {
        name: "Olive Oil",
        unit: "1L",
        price: 850,
        image: "https://res.cloudinary.com/demo/image/upload/olive_oil.jpg",
        categoryName: "Cooking",
    },
    {
        name: "Sunflower Oil",
        unit: "1L",
        price: 160,
        image: "https://res.cloudinary.com/demo/image/upload/sunflower_oil.jpg",
        categoryName: "Cooking",
    },
    {
        name: "Salt",
        unit: "1kg",
        price: 25,
        image: "https://res.cloudinary.com/demo/image/upload/salt.jpg",
        categoryName: "Cooking",
    },
    {
        name: "Sugar",
        unit: "2kg",
        price: 90,
        image: "https://res.cloudinary.com/demo/image/upload/sugar.jpg",
        categoryName: "Cooking",
    },
    {
        name: "Flour",
        unit: "5kg",
        price: 220,
        image: "https://res.cloudinary.com/demo/image/upload/flour.jpg",
        categoryName: "Cooking",
    },
    {
        name: "Rice",
        unit: "5kg",
        price: 320,
        image: "https://res.cloudinary.com/demo/image/upload/rice.jpg",
        categoryName: "Cooking",
    },

    // ================= BREAKFAST =================
    {
        name: "Chips",
        unit: "500g",
        price: 150,
        image: "https://res.cloudinary.com/demo/image/upload/chips.jpg",
        categoryName: "Breakfast",
    },
    {
        name: "Popcorn",
        unit: "1kg",
        price: 180,
        image: "https://res.cloudinary.com/demo/image/upload/popcorn.jpg",
        categoryName: "Breakfast",
    },

    // ================= BEVERAGE =================
    {
        name: "Orange Juice",
        unit: "1L",
        price: 120,
        image: "https://res.cloudinary.com/demo/image/upload/orange_juice.jpg",
        categoryName: "Beverage",
    },
    {
        name: "Apple Juice",
        unit: "1L",
        price: 125,
        image: "https://res.cloudinary.com/demo/image/upload/apple_juice.jpg",
        categoryName: "Beverage",
    },
    {
        name: "Smoothie",
        unit: "250ml",
        price: 180,
        image: "https://res.cloudinary.com/demo/image/upload/smoothie.jpg",
        categoryName: "Beverage",
    },
    {
        name: "Coconut Water",
        unit: "500ml",
        price: 65,
        image: "https://res.cloudinary.com/demo/image/upload/coconut_water.jpg",
        categoryName: "Beverage",
    },
    {
        name: "Energy Drink",
        unit: "250ml",
        price: 110,
        image: "https://res.cloudinary.com/demo/image/upload/energy_drink.jpg",
        categoryName: "Beverage",
    },

    // ================= HEALTH & BEAUTY =================
    {
        name: "Toothpaste",
        unit: "150g",
        price: 110,
        image: "https://res.cloudinary.com/demo/image/upload/toothpaste.jpg",
        categoryName: "Health & Beauty",
    },
    {
        name: "Toothbrush",
        unit: "1 pc",
        price: 80,
        image: "https://res.cloudinary.com/demo/image/upload/toothbrush.jpg",
        categoryName: "Health & Beauty",
    },
    {
        name: "Deodorant",
        unit: "150ml",
        price: 220,
        image: "https://res.cloudinary.com/demo/image/upload/deodorant.jpg",
        categoryName: "Health & Beauty",
    },
    {
        name: "Hand Cream",
        unit: "50ml",
        price: 180,
        image: "https://res.cloudinary.com/demo/image/upload/hand_cream.jpg",
        categoryName: "Health & Beauty",
    },
    {
        name: "Shaving Gel",
        unit: "200ml",
        price: 210,
        image: "https://res.cloudinary.com/demo/image/upload/shaving_gel.jpg",
        categoryName: "Health & Beauty",
    },
];