export const sportsProducts = [
    // 🏋️ FITNESS
    {
        name: "Yoga Mat",
        unit: "1 pc",
        price: 799,
        image: "https://res.cloudinary.com/demo/image/upload/yoga-mat.png",
        categorySlug: "fitness",
    },
    {
        name: "Dumbbell Set",
        unit: "1 set",
        price: 2999,
        image: "https://res.cloudinary.com/demo/image/upload/dumbbell-set.png",
        categorySlug: "fitness",
    },
    {
        name: "Resistance Bands",
        unit: "1 set",
        price: 899,
        image: "https://res.cloudinary.com/demo/image/upload/resistance-bands.png",
        categorySlug: "fitness",
    },
    {
        name: "Kettlebell",
        unit: "1 pc",
        price: 1799,
        image: "https://res.cloudinary.com/demo/image/upload/kettlebell.png",
        categorySlug: "fitness",
    },
    {
        name: "Skipping Rope",
        unit: "1 pc",
        price: 349,
        image: "https://res.cloudinary.com/demo/image/upload/skipping-rope.png",
        categorySlug: "fitness",
    },
    {
        name: "Foam Roller",
        unit: "1 pc",
        price: 999,
        image: "https://res.cloudinary.com/demo/image/upload/foam-roller.png",
        categorySlug: "fitness",
    },
    {
        name: "Push-up Bars",
        unit: "1 pair",
        price: 599,
        image: "https://res.cloudinary.com/demo/image/upload/pushup-bars.png",
        categorySlug: "fitness",
    },
    {
        name: "Workout Gloves",
        unit: "1 pair",
        price: 699,
        image: "https://res.cloudinary.com/demo/image/upload/workout-gloves.png",
        categorySlug: "fitness",
    },
    {
        name: "Medicine Ball",
        unit: "1 pc",
        price: 1999,
        image: "https://res.cloudinary.com/demo/image/upload/medicine-ball.png",
        categorySlug: "fitness",
    },

    // 🏕️ OUTDOOR
    {
        name: "Camping Lantern",
        unit: "1 pc",
        price: 1199,
        image: "https://res.cloudinary.com/demo/image/upload/camping-lantern.png",
        categorySlug: "outdoor",
    },
    {
        name: "Sleeping Bag",
        unit: "1 pc",
        price: 2499,
        image: "https://res.cloudinary.com/demo/image/upload/sleeping-bag.png",
        categorySlug: "outdoor",
    },
    {
        name: "Hiking Backpack",
        unit: "1 pc",
        price: 3499,
        image: "https://res.cloudinary.com/demo/image/upload/hiking-backpack.png",
        categorySlug: "outdoor",
    },
    {
        name: "Camping Tent",
        unit: "1 pc",
        price: 5999,
        image: "https://res.cloudinary.com/demo/image/upload/camping-tent.png",
        categorySlug: "outdoor",
    },
    {
        name: "Portable Stove",
        unit: "1 pc",
        price: 1999,
        image: "https://res.cloudinary.com/demo/image/upload/portable-stove.png",
        categorySlug: "outdoor",
    },
    {
        name: "Thermal Flask",
        unit: "1 pc",
        price: 899,
        image: "https://res.cloudinary.com/demo/image/upload/thermal-flask.png",
        categorySlug: "outdoor",
    },
    {
        name: "Compass",
        unit: "1 pc",
        price: 299,
        image: "https://res.cloudinary.com/demo/image/upload/compass.png",
        categorySlug: "outdoor",
    },
    {
        name: "Camping Chair",
        unit: "1 pc",
        price: 1799,
        image: "https://res.cloudinary.com/demo/image/upload/camping-chair.png",
        categorySlug: "outdoor",
    },

    // 🚴 CYCLING
    {
        name: "Cycling Helmet",
        unit: "1 pc",
        price: 1499,
        image: "https://res.cloudinary.com/demo/image/upload/cycling-helmet.png",
        categorySlug: "cycling",
    },
    {
        name: "Mountain Cycle",
        unit: "1 pc",
        price: 14999,
        image: "https://res.cloudinary.com/demo/image/upload/mountain-cycle.png",
        categorySlug: "cycling",
    },
    {
        name: "Bike Gloves",
        unit: "1 pair",
        price: 599,
        image: "https://res.cloudinary.com/demo/image/upload/bike-gloves.png",
        categorySlug: "cycling",
    },
    {
        name: "Cycling Jersey",
        unit: "1 pc",
        price: 1299,
        image: "https://res.cloudinary.com/demo/image/upload/cycling-jersey.png",
        categorySlug: "cycling",
    },
    {
        name: "Bike Lock",
        unit: "1 pc",
        price: 799,
        image: "https://res.cloudinary.com/demo/image/upload/bike-lock.png",
        categorySlug: "cycling",
    },
    {
        name: "Water Bottle Cage",
        unit: "1 pc",
        price: 349,
        image: "https://res.cloudinary.com/demo/image/upload/water-bottle-cage.png",
        categorySlug: "cycling",
    },
    {
        name: "Bike Pump",
        unit: "1 pc",
        price: 699,
        image: "https://res.cloudinary.com/demo/image/upload/bike-pump.png",
        categorySlug: "cycling",
    },

    // ⚽ BALL SPORTS
    {
        name: "Football",
        unit: "1 pc",
        price: 899,
        image: "https://res.cloudinary.com/demo/image/upload/football.png",
        categorySlug: "ball",
    },
    {
        name: "Cricket Bat",
        unit: "1 pc",
        price: 2499,
        image: "https://res.cloudinary.com/demo/image/upload/cricket-bat.png",
        categorySlug: "ball",
    },
    {
        name: "Basketball",
        unit: "1 pc",
        price: 1199,
        image: "https://res.cloudinary.com/demo/image/upload/basketball.png",
        categorySlug: "ball",
    },
    {
        name: "Tennis Ball Pack",
        unit: "3 pcs",
        price: 399,
        image: "https://res.cloudinary.com/demo/image/upload/tennis-ball-pack.png",
        categorySlug: "ball",
    },
    {
        name: "Badminton Shuttle",
        unit: "6 pcs",
        price: 499,
        image: "https://res.cloudinary.com/demo/image/upload/badminton-shuttle.png",
        categorySlug: "ball",
    },
    {
        name: "Volleyball",
        unit: "1 pc",
        price: 999,
        image: "https://res.cloudinary.com/demo/image/upload/volleyball.png",
        categorySlug: "ball",
    },
    {
        name: "Table Tennis Bat",
        unit: "1 pc",
        price: 799,
        image: "https://res.cloudinary.com/demo/image/upload/table-tennis-bat.png",
        categorySlug: "ball",
    },

    // 👕 WEAR
    {
        name: "Running T-Shirt",
        unit: "1 pc",
        price: 699,
        image: "https://res.cloudinary.com/demo/image/upload/running-tshirt.png",
        categorySlug: "wear",
    },
    {
        name: "Sports Shorts",
        unit: "1 pc",
        price: 799,
        image: "https://res.cloudinary.com/demo/image/upload/sports-shorts.png",
        categorySlug: "wear",
    },
    {
        name: "Track Pants",
        unit: "1 pc",
        price: 1199,
        image: "https://res.cloudinary.com/demo/image/upload/track-pants.png",
        categorySlug: "wear",
    },
    {
        name: "Training Jacket",
        unit: "1 pc",
        price: 1999,
        image: "https://res.cloudinary.com/demo/image/upload/training-jacket.png",
        categorySlug: "wear",
    },
    {
        name: "Sports Cap",
        unit: "1 pc",
        price: 399,
        image: "https://res.cloudinary.com/demo/image/upload/sports-cap.png",
        categorySlug: "wear",
    },
    {
        name: "Ankle Socks",
        unit: "3 pairs",
        price: 299,
        image: "https://res.cloudinary.com/demo/image/upload/ankle-socks.png",
        categorySlug: "wear",
    },
    {
        name: "Gym Vest",
        unit: "1 pc",
        price: 499,
        image: "https://res.cloudinary.com/demo/image/upload/gym-vest.png",
        categorySlug: "wear",
    },
    {
        name: "Sports Shoes",
        unit: "1 pair",
        price: 3499,
        image: "https://res.cloudinary.com/demo/image/upload/sports-shoes.png",
        categorySlug: "wear",
    },
];